### ISSUE TITLE
请问一下作者ratios: [50, 200]是什么作用？

### ISSUE THREAD

**Issue by Fangzhenxuan** [greatlog/UnpairedSR#11]
https://github.com/greatlog/UnpairedSR/blob/b6d0c05ad327f8aa4118aab852a49d94e0b80ac7/codes/config/PDM-SR/options/train/percep/2020Track2.yml#L16

**Comment by greatlog** [comment]
作用有二
1. 调节src图片数据数量和tgt图片数量不相等的问题，详见 [#12](https://github.com/greatlog/UnpairedSR/issues/12#issuecomment-1076478754)

2.将数据集图片重复多次，以增多一个epoch内的迭代次数，从而可以减少整个训练周期的epoch数，从而减少每个epoch开始前的等待时间和dataset中drop laset的影响。
