### ISSUE TITLE
why result of inference.py is all black

### ISSUE THREAD

**Issue by zhangyunming** [greatlog/UnpairedSR#13]
?

**Comment by LiYAnErr** [comment]
因为crop_size的大小可能超过了你的测试图像。必须得测试图像的长x宽能够整除crop_size x crop_size，才能正常显示。

**Comment by zhangyunming** [comment]
我就测试了lR下默认的图是256*512的，我吧crop改成256  也是黑的
我又实验了512*512的图  crop是512   也还是黑的

**Comment by LiYAnErr** [comment]
我是修改了他们的文件，我发现有个错误：
codes/config/PDM-SR/models/deg_sr_model.py的第294-295行和第314-315行里的range要改成：
- h_start = list(range(0, h-crop_size +1 , crop_size))
- 注意就是这个+1，保证了可以读取到h-crop_size

修改之后，crop_size设置成256，用该仓库里的LR图像，就可以正常出结果了。

**Comment by greatlog** [comment]
你试试把crop去掉，默认是None。

代码逻辑是 crop size需要比图小，你的图短边是256，会导致crop size=256的时候直接跳过模型测试了。算是一个小bug，我后面会修一下。

如果图比较小，可以不用crop，就是把crop设置成None。

**Comment by zhangyunming** [comment]
改成=None 就可以了
