### ISSUE TITLE
作者您好，请问带入自己的数据集进行训练，操作流程应当是怎么样的？

### ISSUE THREAD

**Issue by LiYAnErr** [greatlog/UnpairedSR#14]
目前我使用的流程是这样的：
（1）调用codes/scripts/create_lmdb.py，为我的数据集生成对应的lmdb文件
（2）以codes/config/PDM-SR/options/train/percep/2020Track2.yml配置为参照，更改其中的数据集路径，得到我的配置文件xx.yml
（3）使用python train.py --opt options/train/percep/xx.yml，开启训练。

请问作者上述流程是否有错误？谢谢～

**Comment by greatlog** [comment]
是这样的。

**Comment by xuhuiling999** [comment]
FileNotFoundError: [Errno 2] No such file or directory: '/SRDataset/DIV2K_train_HR_x4_new.lmdb'
你好 我想问我在调用create_lmdb.py时报了上面这样的错误，是保存图片的.lmdb文件必须提前创建好吗？

**Comment by mrgreen3325** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: '/SRDataset/DIV2K_train_HR_x4_new.lmdb' 你好 我想问我在调用create_lmdb.py时报了上面这样的错误，是保存图片的.lmdb文件必须提前创建好吗？

Hello,
Did you try the percep/2020Track2.yml training?
Someone said there are errors for training
https://github.com/greatlog/UnpairedSR/issues/18
