### ISSUE TITLE
作者，你好！     inference.py 求助

### ISSUE THREAD

**Issue by xpo0a** [greatlog/UnpairedSR#16]
'''
cd codes/config/PDM-SR/
python3 inference.py --opt options/test/2020Track2.yml
'''
checkpoint模型已下载，修改了2020Track2.ymal中的dataroot为自己路径。
但是生成11张图像全为7.9kb大小的纯黑图，请问是什么问题导致 ？

**Comment by greatlog** [comment]
可以参考 [#13](https://github.com/greatlog/UnpairedSR/issues/13)

**Comment by xpo0a** [comment]
多谢
