### ISSUE TITLE
单独训练测试PDM

### ISSUE THREAD

**Issue by Zhenxing-Dong** [greatlog/UnpairedSR#2]
你好，请问如何单独训练和测试PDM模块啊？按照/UnpairedSR-master/codes/config/PDM-SR/options/train/deg下的yml文件，训练PDM，却报错在val的时候没有netSR。

**Comment by greatlog** [comment]
deg下面是单独训练PDM的配置，optim_deg=True, optim_sr=False。因为validation是针对SR做的，训练deg的时候没有添加netSR，所以validation没法做。你可以把val_freq改成和 niter 一样大，这样就不会在训练时做 validation了。

**Comment by Zhenxing-Dong** [comment]
那请问可以对PDM进行单独测试吗？我看test下面都是针对SR的。

**Comment by greatlog** [comment]
除了使用PDM帮助训练超分模型，我没想到其他办法可以很好的衡量PDM的性能，因为PDM没有真正意义上的GT。训练好的PDM可以单独运行，大图进，小图出，但是训练过程中没法validation。如果大家有什么好的建议欢迎提PR。

**Comment by zhh99** [comment]
@greatlog 您好，文中说PDM与SR可以同时训练，实际训练时，仍然采用单独训练是吗？因为我看代码options/train/psnr下的yml文件里的optim_deg为false
