### ISSUE TITLE
请问为什么没有与DASR(CVPR2020)，DeFlow(CVPR2021)，DAP(ICCV2021)等unpaired低分辨率数据生成方法进行对比？

### ISSUE THREAD

**Issue by wonderland859** [greatlog/UnpairedSR#4]

**Comment by greatlog** [comment]
DASR使用的数据生成方式是DSGAN，为了公平对比，我们把超分模型统一成了EDSR，也即论文中的 DSGAN-SR。
DAP的数据生成模型和超分模型是一体的，没办法单独拆开替换超分模型进行公平比较。当然也可以使用原模型训练，但是按我的理解，这种用在人脸超分中的模型放在通用超分中应该是不行的，原因在于人脸超分中，模型很容易学到人脸的先验，然而通用超分中，由于图片的多样性，学到类似的先验很难，这也是为什么目前很多人脸超分模型在通用超分中表现平平。
关于DeFlow确实是我们的疏忽，在做工作的时候没有注意到这篇论文，感谢提醒，后面我们会考虑做同样的量化对比，也欢迎大家提PR。

**Comment by jingzhutang** [comment]
DAP 目前没有 official implementation 的代码开源，此外它也是一篇真实超分辨率的文章，文章名为 Unsupervised Real-World Super-Resolution: A Domain Adaptation Perspective；
另外对于DASR、NTIRE2020比赛那年的冠军、BSRGAN、RealESRGAN它们的超分模型都是RRDBNet + GAN；所以作者的意思是说与BSRGAN、RealESRGAN、NTIRE2020比赛那年的冠军比较的时候超分模型也换成了EDSR吗？

**Comment by greatlog** [comment]
我以为是你说的DAP是这篇：[Super-Resolving Cross-Domain Face Miniatures by Peeking at One-Shot Exemplar](!https://arxiv.org/abs/2103.08863)。你说的字节那篇我们也看了，文章出来的时候我们已经完成了大部分实验工作，考虑字节那篇也是基于CycleGAN，性能可能和CycleSR类似，所以没有进一步添加相关对比。我们可以在我们的code base里进行复现。

我们的Table2中的方法使用的超分模型都是EDSR，Table3中的用的都是RRDB。DASR在数据生成方面沿用的是类似[Frequency Separation]中的DSRGAN，所以我们仅仅在Table2中比较了DSRGAN-SR。考虑到DASR提出的超分训练技术同样可以叠加到其他方法上，而我们的重点在研究数据合成，所以没有单独比较DASR。

**Comment by wonderland859** [comment]
嗯嗯，好的，感谢耐心的回复。
