### ISSUE TITLE
用作者提供的checkpoint在2020Track2测试集上没有达到论文中结果

### ISSUE THREAD

**Issue by Fangzhenxuan** [greatlog/UnpairedSR#6]
22-03-21 00:36:02.734 - INFO: Average Results for 2020Track2
niqe: 3.884121; 
22-03-21 00:36:02.735 - INFO: Average Results on Y channel for 2020Track2
niqe: 3.918726; 

论文中2020Track2测试集的NIQE为3.19，但是用 test.py --opt options/test/2020Track2.yml 测出来的结果低了，请问一下是我哪里出了问题吗，其他测试集上的checkpoints能否一并放出？

**Comment by greatlog** [comment]
目前我们提供的ckpt是按视觉最优提供的，论文表格中的ckpt还在整理中，后面会陆续放出。

**Comment by Fangzhenxuan** [comment]
好的，感谢回复

**Comment by greatlog** [comment]
已上传。
