### ISSUE TITLE
KeyError: 'netDeg'

### ISSUE THREAD

**Issue by ZYQii** [greatlog/UnpairedSR#8]
作者您好，我在运行Start up里的“python3 inference.py --opt options/test/2020Track2.yml”代码行时，遇到报错：
export CUDA_VISIBLE_DEVICES=0
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "inference.py", line 57, in <module>
    model.test({"src": img_t}, crop_size=512)
  File "/home/bobo/home/bobo/F/z/UnpairedSR/codes/config/PDM-SR/models/deg_sr_model.py", line 264, in test
    self.set_network_state(["netDeg", "netSR"], "eval")
  File "/home/bobo/home/bobo/F/z/UnpairedSR/codes/config/PDM-SR/models/base_model.py", line 184, in set_network_state
    if isinstance(self.networks[name], nn.Module):
KeyError: 'netDeg'
请问如何解决？谢谢

**Comment by greatlog** [comment]
可更新代码后重试。

**Comment by qiqi450** [comment]
> 作者您好，我在运行Start up里的“python3 inference.py --opt options/test/2020Track2.yml”代码行时，遇到报错： export CUDA_VISIBLE_DEVICES=0 0it [00:00, ?it/s] Traceback (most recent call last): File "inference.py", line 57, in model.test({"src": img_t}, crop_size=512) File "/home/bobo/home/bobo/F/z/UnpairedSR/codes/config/PDM-SR/models/deg_sr_model.py", line 264, in test self.set_network_state(["netDeg", "netSR"], "eval") File "/home/bobo/home/bobo/F/z/UnpairedSR/codes/config/PDM-SR/models/base_model.py", line 184, in set_network_state if isinstance(self.networks[name], nn.Module): KeyError: 'netDeg' 请问如何解决？谢谢

**Comment by qiqi450** [comment]
> 作者您好，我在运行Start up里的“python3 inference.py --opt options/test/2020Track2.yml”代码行时，遇到报错： export CUDA_VISIBLE_DEVICES=0 0it [00:00, ?it/s] Traceback (most recent call last): File "inference.py", line 57, in model.test({"src": img_t}, crop_size=512) File "/home/bobo/home/bobo/F/z/UnpairedSR/codes/config/PDM-SR/models/deg_sr_model.py", line 264, in test self.set_network_state(["netDeg", "netSR"], "eval") File "/home/bobo/home/bobo/F/z/UnpairedSR/codes/config/PDM-SR/models/base_model.py", line 184, in set_network_state if isinstance(self.networks[name], nn.Module): KeyError: 'netDeg' 请问如何解决？谢谢

你好，请问解决了吗，我也遇到了同样的问题
