### ISSUE TITLE
在run train.py时遇到了下面的问题

### ISSUE THREAD

**Issue by Fangzhenxuan** [greatlog/UnpairedSR#9]
在执行 python train.py --opt options/train/percep/2020Track2.yml时，出现了如下报错
f"No object named '{name}' found in '{self._name}' registry!"
KeyError: "No object named 'MultiStepLR' found in 'lr_scheduler' registry!"

请问作者遇到过吗，如何解决？

**Comment by greatlog** [comment]
已fix相关bug。如果你需要端到端训练PDM-SR，我暂时先更新了percep/2020Track2.yml 的相应内容，可以按这个配置进行训练。其他的option文件暂时还没修改，部分训练细节暂时还未添加，后面我会抽空慢慢更新。
